logger:
    file: /var/log/open5gs/amf.log
    #level: debug
    #domain: sb
amf:
    sbi:
    - addr: 0.0.0.0
      advertise: open5gs-amf
    ngap:
      dev: eth0
    guami:
    - plmn_id:
        mcc: 208
        mnc: 93
      amf_id:
        region: 2
        set: 1
    tai:
    - plmn_id:
        mcc: 208
        mnc: 93
      tac: 7
    plmn_support:
    - plmn_id:
        mcc: 208
        mnc: 93
      s_nssai:
      - sst: 1
        sd: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf
nrf:
 sbi:
   name: open5gs-nrf